# Generated by Django 4.1.5 on 2023-01-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
    ]
