# Generated by Django 4.1.5 on 2023-01-26 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_whislist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whislist',
            new_name='Whishlist',
        ),
    ]
